In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving players.csv to players.csv
User uploaded file "players.csv" with length 39885900 bytes

In [ ]:
import csv
import pandas as pd
players = pd.read_csv("players.csv")
players.head()

   player_api_id                 date  ...  gk_positioning  gk_reflexes
0         505942  2016-02-18 00:00:00  ...             8.0          8.0
1         505942  2015-11-19 00:00:00  ...             8.0          8.0
2         505942  2015-09-21 00:00:00  ...             8.0          8.0
3         505942  2015-03-20 00:00:00  ...             7.0          7.0
4         505942  2007-02-22 00:00:00  ...             7.0          7.0

[5 rows x 40 columns]

In [ ]:
players.describe()

       player_api_id  overall_rating  ...  gk_positioning    gk_reflexes
count  183978.000000   183142.000000  ...   183142.000000  183142.000000
mean   135900.617324       68.600015  ...       16.132154      16.441439
std    136927.840510        7.041139  ...       16.099175      17.198155
min      2625.000000       33.000000  ...        1.000000       1.000000
25%     34763.000000       64.000000  ...        8.000000       8.000000
50%     77741.000000       69.000000  ...       11.000000      11.000000
75%    191080.000000       73.000000  ...       15.000000      15.000000
max    750584.000000       94.000000  ...       96.000000      96.000000

[8 rows x 36 columns]

In [ ]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183978 entries, 0 to 183977
Data columns (total 40 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   player_api_id        183978 non-null  int64
 1   date                 183978 non-null  object
 2   overall_rating       183142 non-null  float64
 3   potential            183142 non-null  float64
 4   preferred_foot       183142 non-null  object
 5   attacking_work_rate  180748 non-null  object
 6   defensive_work_rate  183142 non-null  object
 7   crossing             183142 non-null  float64
 8   finishing            183142 non-null  float64
 9   heading_accuracy     183142 non-null  float64
 10  short_passing        183142 non-null  float64
 11  volleys              181265 non-null  float64
 12  dribbling            183142 non-null  float64
 13  curve                181265 non-null  float64
 14  free_kick_accuracy   183142 non-null  float64
 15  long_passing         183142 non-null  float64
 16  ball_control         183142 non-null  float64
 17  acceleration         183142 non-null  float64
 18  sprint_speed         183142 non-null  float64
 19  agility              181265 non-null  float64
 20  reactions            183142 non-null  float64
 21  balance              181265 non-null  float64
 22  shot_power           183142 non-null  float64
 23  jumping              181265 non-null  float64
 24  stamina              183142 non-null  float64
 25  strength             183142 non-null  float64
 26  long_shots           183142 non-null  float64
 27  aggression           183142 non-null  float64
 28  interceptions        183142 non-null  float64
 29  positioning          183142 non-null  float64
 30  vision               181265 non-null  float64
 31  penalties            183142 non-null  float64
 32  marking              183142 non-null  float64
 33  standing_tackle      183142 non-null  float64
 34  sliding_tackle       181265 non-null  float64
 35  gk_diving            183142 non-null  float64
 36  gk_handling          183142 non-null  float64
 37  gk_kicking           183142 non-null  float64
 38  gk_positioning       183142 non-null  float64
 39  gk_reflexes          183142 non-null  float64
dtypes: float64(35), int64(1), object(4)
memory usage: 56.1+ MB

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving data.csv to data.csv
User uploaded file "data.csv" with length 2460672 bytes

In [ ]:
import csv
import pandas as pd
data = pd.read_csv("data.csv")
data.head()

   id  home_player_1  home_player_2  home_player_3  ...   BSD  BSA  year  win_team
0   0          25524          30668          27293  ...  3.75  7.0  2008         1
1   1          41671          18823          25526  ...  0.00  0.0  2016         0
2   2          46704         193807         426878  ...  0.00  0.0  2015         0
3   3          41301         166679         280083  ...  0.00  0.0  2015         1
4   4          69650          32870          30890  ...  0.00  0.0  2014         1

[5 rows x 55 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8786 entries, 0 to 8785
Data columns (total 55 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              8786 non-null   int64
 1   home_player_1   8786 non-null   int64
 2   home_player_2   8786 non-null   int64
 3   home_player_3   8786 non-null   int64
 4   home_player_4   8786 non-null   int64
 5   home_player_5   8786 non-null   int64
 6   home_player_6   8786 non-null   int64
 7   home_player_7   8786 non-null   int64
 8   home_player_8   8786 non-null   int64
 9   home_player_9   8786 non-null   int64
 10  home_player_10  8786 non-null   int64
 11  home_player_11  8786 non-null   int64
 12  away_player_1   8786 non-null   int64
 13  away_player_2   8786 non-null   int64
 14  away_player_3   8786 non-null   int64
 15  away_player_4   8786 non-null   int64
 16  away_player_5   8786 non-null   int64
 17  away_player_6   8786 non-null   int64
 18  away_player_7   8786 non-null   int64
 19  away_player_8   8786 non-null   int64
 20  away_player_9   8786 non-null   int64
 21  away_player_10  8786 non-null   int64
 22  away_player_11  8786 non-null   int64
 23  B365H           8786 non-null   float64
 24  B365D           8786 non-null   float64
 25  B365A           8786 non-null   float64
 26  BWH             8786 non-null   float64
 27  BWD             8786 non-null   float64
 28  BWA             8786 non-null   float64
 29  IWH             8786 non-null   float64
 30  IWD             8786 non-null   float64
 31  IWA             8786 non-null   float64
 32  LBH             8786 non-null   float64
 33  LBD             8786 non-null   float64
 34  LBA             8786 non-null   float64
 35  PSH             8786 non-null   float64
 36  PSD             8786 non-null   float64
 37  PSA             8786 non-null   float64
 38  WHH             8786 non-null   float64
 39  WHD             8786 non-null   float64
 40  WHA             8786 non-null   float64
 41  SJH             8786 non-null   float64
 42  SJD             8786 non-null   float64
 43  SJA             8786 non-null   float64
 44  VCH             8786 non-null   float64
 45  VCD             8786 non-null   float64
 46  VCA             8786 non-null   float64
 47  GBH             8786 non-null   float64
 48  GBD             8786 non-null   float64
 49  GBA             8786 non-null   float64
 50  BSH             8786 non-null   float64
 51  BSD             8786 non-null   float64
 52  BSA             8786 non-null   float64
 53  year            8786 non-null   int64
 54  win_team        8786 non-null   int64
dtypes: float64(30), int64(25)
memory usage: 3.7 MB

In [ ]:
data.describe()

                id  home_player_1  ...         year     win_team
count  8786.000000    8786.000000  ...  8786.000000  8786.000000
mean   4392.500000   76909.822900  ...  2012.272251     0.615183
std    2536.444066   88044.447448  ...     2.271568     0.486580
min       0.000000    2984.000000  ...  2008.000000     0.000000
25%    2196.250000   30633.000000  ...  2010.000000     0.000000
50%    4392.500000   37900.000000  ...  2012.000000     1.000000
75%    6588.750000   96651.000000  ...  2014.000000     1.000000
max    8785.000000  698273.000000  ...  2016.000000     1.000000

[8 rows x 55 columns]

In [ ]:
data.columns

Index(['id', 'home_player_1', 'home_player_2', 'home_player_3',
       'home_player_4', 'home_player_5', 'home_player_6', 'home_player_7',
       'home_player_8', 'home_player_9', 'home_player_10', 'home_player_11',
       'away_player_1', 'away_player_2', 'away_player_3', 'away_player_4',
       'away_player_5', 'away_player_6', 'away_player_7', 'away_player_8',
       'away_player_9', 'away_player_10', 'away_player_11', 'B365H', 'B365D',
       'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA',
       'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH',
       'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA', 'year',
       'win_team'],
      dtype='object')

In [ ]:
len(data.columns)

30

In [ ]:
y = data['win_team']

In [ ]:
data.drop(['id', 'home_player_1', 'home_player_2', 'home_player_3',
       'home_player_4', 'home_player_5', 'home_player_6', 'home_player_7',
       'home_player_8', 'home_player_9', 'home_player_10', 'home_player_11',
       'away_player_1', 'away_player_2', 'away_player_3', 'away_player_4',
       'away_player_5', 'away_player_6', 'away_player_7', 'away_player_8',
       'away_player_9', 'away_player_10', 'away_player_11', 'year', 'win_team'], axis=1, inplace=True)

In [ ]:
data

      B365H  B365D  B365A   BWH   BWD   BWA  ...   GBH   GBD   GBA   BSH   BSD   BSA
0      1.44   4.20   7.50  1.40  4.15  7.00  ...  1.44  3.75  8.00  1.44  3.75  7.00
1      1.91   3.30   4.50  1.85  3.30  4.40  ...  0.00  0.00  0.00  0.00  0.00  0.00
2      2.40   3.10   3.20  2.50  3.10  2.85  ...  0.00  0.00  0.00  0.00  0.00  0.00
3      1.57   3.80   6.00  1.55  4.00  5.75  ...  0.00  0.00  0.00  0.00  0.00  0.00
4      2.30   3.30   3.50  2.35  3.10  3.10  ...  0.00  0.00  0.00  0.00  0.00  0.00
...     ...    ...    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
8781   2.05   3.40   3.50  1.95  3.30  3.55  ...  2.10  3.30  3.50  2.05  3.30  3.25
8782   1.53   3.80   6.50  1.53  3.70  6.75  ...  0.00  0.00  0.00  0.00  0.00  0.00
8783   2.20   3.30   3.25  2.25  3.40  3.10  ...  0.00  0.00  0.00  0.00  0.00  0.00
8784   1.44   4.33   7.00  1.50  4.25  6.75  ...  1.44  4.00  7.00  1.50  4.00  6.00
8785   6.50   3.75   1.57  5.40  3.45  1.60  ...  6.00  3.30  1.65  6.00  3.60  1.57

[8786 rows x 30 columns]

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier

X_train, X_holdout, y_train, y_holdout = train_test_split(data.values, y, test_size=0.2,
random_state=17)

tree = DecisionTreeClassifier(random_state=17)
knn = KNeighborsClassifier(n_neighbors=10)

tree.fit(X_train, y_train)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [ ]:
from sklearn.metrics import accuracy_score

tree_pred = tree.predict(X_holdout)
accuracy_score(y_holdout, tree_pred)

0.626848691695108

In [ ]:
knn_pred = knn.predict(X_holdout)
accuracy_score(y_holdout, knn_pred)

0.6780432309442548

In [ ]:
from sklearn.model_selection import GridSearchCV, cross_val_score

In [ ]:
tree_params = {'max_depth': range(3,30),
'max_features': range(4,30)}

In [ ]:
tree_grid = GridSearchCV(tree, tree_params,
cv=5, n_jobs=-1,
verbose=True)

In [ ]:
tree_grid.fit(X_train, y_train)

Fitting 5 folds for each of 702 candidates, totalling 3510 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 330 tasks      | elapsed:    5.2s
[Parallel(n_jobs=-1)]: Done 1694 tasks      | elapsed:   39.0s
[Parallel(n_jobs=-1)]: Done 2694 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 3510 out of 3510 | elapsed:  1.8min finished

GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=17,
                                              splitter='best'),
             iid='deprecated', n_jobs=-1,
             param_grid={'max_depth': range(3, 30),
                         'max_features': range(4, 30)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=True)

In [ ]:
tree_grid.best_params_

{'max_depth': 3, 'max_features': 13}

In [ ]:
tree_grid.best_score_

0.6967844975524317

In [ ]:
accuracy_score(y_holdout, tree_grid.predict(X_holdout))

0.7143399089529591

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
knn_pipe = Pipeline([('scaler', StandardScaler()), ('knn', KNeighborsClassifier(n_jobs=-1))])

In [ ]:
knn_params = {'knn__n_neighbors': range(1, 10)}

In [ ]:
knn_grid = GridSearchCV(knn_pipe, knn_params,
cv=5, n_jobs=-1,
verbose=True)

In [ ]:
knn_grid.fit(X_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:    5.1s finished

GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('scaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('knn',
                                        KNeighborsClassifier(algorithm='auto',
                                                             leaf_size=30,
                                                             metric='minkowski',
                                                             metric_params=None,
                                                             n_jobs=-1,
                                                             n_neighbors=5, p=2,
                                                             weights='uniform'))],
                                verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'knn__n_neighbors': range(1, 10)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=True)

In [ ]:
knn_grid.best_params_, knn_grid.best_score_

({'knn__n_neighbors': 9}, 0.6741463414634146)

In [ ]:
accuracy_score(y_holdout, knn_grid.predict(X_holdout))

0.6764036418816388

In [ ]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
forest = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=17)
print(np.mean(cross_val_score(forest, X_train, y_train, cv=5)))

0.6788617886178863

In [ ]:
forest_params = {'max_depth': range(1,11),
'max_features': range(4,19)}

In [ ]:
forest_grid = GridSearchCV(forest, forest_params,
cv=5, n_jobs=-1,
verbose=True)

In [ ]:
forest_grid.fit(X_train, y_train)

Fitting 5 folds for each of 150 candidates, totalling 750 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 446 tasks      | elapsed:  3.8min
[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed:  8.6min finished

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=-1,
                                              oob_score=False, random_state=17,
                                              verbose=0, warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'max_depth': range(1, 11),
                         'max_features': range(4, 19)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=True)

In [ ]:
forest_grid.fit(X_train, y_train)

Fitting 5 folds for each of 150 candidates, totalling 750 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   14.5s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 446 tasks      | elapsed:  3.9min
[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed:  8.6min finished

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=-1,
                                              oob_score=False, random_state=17,
                                              verbose=0, warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'max_depth': range(1, 11),
                         'max_features': range(4, 19)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=True)

In [ ]:
accuracy_score(y_holdout, forest_grid.predict(X_holdout))

0.7113050075872535